name: Pull requests

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.5.3
      - uses: nanasess/setup-chromedriver@master
      
      - run: flutter --version
      - run: flutter pub get
      - run: flutter test --coverage
      - run: flutter test --platform chrome
      - run: flutter test
      
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        env:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: michaelopes/simple_navigator 